会場を株式会社インプレイスに更新した
ayachimu/ichiyasaGitSample pull request #1
Opened 2023-10-07 07:23 UTC by ayachimu

### 変更内容
イベント開催会場を「株式会社インプレイス」に更新しました。

### 背景
「株式会社インプレイス」さんがイベント会場を提供してくださることになりました。

2023-10-07 07:26 UTC, jupemara requested changes
ただのコメントなので変更なくてもそのまま merge してもらって大丈夫です.

2023-10-07 07:26 UTC, jupemara commented on index.html
> +                        <p>株式会社インプレイス イベントセミナー会場</p>
pタグ = paragraph なので, ここでは `<div>` を代わりに使うのはどうでしょう??

2023-10-07 07:27 UTC, jupemara approved these changes
LGTM!!

2023-10-09 01:10 UTC, ayachimu commented
イベント開催会場を「株式会社インプレイス」に更新

2023-10-09 01:10 UTC, merged